### PR TITLE
Logging:  inject logger into ctor of session

### PR DESCRIPTION
**Pull request by PeterDM65**
Instead of creating a logger instance in the ctor of session, i think it's better to inject a logger instance ...

### CODE REVIEW

**Comment by Furtif** [comment]
@PeterDM65 is more simplified :

```csharp
 private void LoggerFucntion(LogLevel logLevel, string message)
        {
            var logtype = LoggerTypes.Debug;
            switch (logLevel)
            {
                case LogLevel.Warn:
                    logtype = LoggerTypes.Warning;
                    break;
                case LogLevel.Error:
                    logtype = LoggerTypes.FatalError;
                    break;
                case LogLevel.Info:
                    logtype = LoggerTypes.Info;
                    break;
                case LogLevel.Notice:
                    logtype = LoggerTypes.Success;
                    break;
            }

            MyLoger_here(message, logtype);
        }
```

on create config and events:

```csharp
var msgStr = "Session couldn't start up.";
                LoggedIn = false;
                try
                {
                    //If ClientSession.ManageResources is set to true
                    ClientSession.AssetDigestUpdated += OnAssetDisgestReceived;
                    ClientSession.ItemTemplatesUpdated += OnItemTemplatesReceived;
                    ClientSession.UrlsUpdated += OnDownloadUrlsReceived;
                    ClientSession.RemoteConfigVersionUpdated += OnLocalConfigVersionReceived;
                    ///
                    ClientSession.AccessTokenUpdated += SessionAccessTokenUpdated;
                    ClientSession.CaptchaReceived += SessionOnCaptchaReceived;
                    ClientSession.InventoryUpdate += SessionInventoryUpdate;
                    ClientSession.MapUpdate += SessionMapUpdate;
                    ClientSession.CheckAwardedBadgesReceived += OnCheckAwardedBadgesReceived;
                    ClientSession.HatchedEggsReceived += OnHatchedEggsReceived;
                    ClientSession.TemporalBanReceived += TempBanReceived;
                    ClientSession.BuddyWalked += OnBuddyWalked;
                    ClientSession.InboxDataReceived += OnInboxDataReceived;
              
                    //Logger is called here
                   ClientSession.Logger.RegisterLogOutput(LoggerFucntion);
                    
                    //enable events for save to local  
                    ClientSession.ManageRessources = My_Config.DownloadResources;
                    MyLoger_here("Succefully added all events to the client.", LoggerTypes.Debug);

                    if (await ClientSession.StartupAsync())
                    {
                        LoggedIn = true;
                        msgStr = "Successfully logged into server.";

                        if (ClientSession.Player.Warn)
                        {

                            MyLoger_heres("The account is flagged.", LoggerTypes.Warning);

                            ClientSession.Shudown();

                              msgStr = "The account is flagged.";
                        }

                        if (ClientSession.Player.Banned)
                        {                           
                            MyLoger_heres("The account is banned.", LoggerTypes.FatalError);

                             ClientSession.Shudown();

                            msgStr = "The account is banned.";
                        }

                        SaveAccessToken(ClientSession.AccessToken);
                    }
                }
                catch (HashVersionMismatchException ex)
                {
                    MyLoger_here(ex.Message, LoggerTypes.Warning);
                    ClientSession.Shutdown();
                }
```
or https://github.com/Furtif/POGOLib/blob/core/POGOLib.Core.Demo.ConsoleApp/Program.cs#L89 and https://github.com/Furtif/POGOLib/blob/core/POGOLib.Core.Demo.ConsoleApp.Multiple/Program.cs#L86 methods

**Comment by PeterDM65** [comment]
I still think it's bad practice to create a logger instance in the ctor of 'session' for following reasons:
- the kind of logger used, does not change the working of the library (=> use an interface)
- you create a dependency on your own implementation. Maybe i like to use Log4Net, NLog, ...
- I can not use the logger before creating the session  (or i have to create a second instance) and called the 'RegisterLogOutput'.
- ...

**Comment by Furtif** [comment]
```csharp
/// Logger in my instance
/// LoggerTypes is my emuns if you not have uses only 
/*
private void LoggerFucntion(LogLevel logLevel, string message)
        {
            MyLoger_here(message, logtype);
        }
*/

private void LoggerFucntion(LogLevel logLevel, string message)
        {
            var logtype = LoggerTypes.Debug;
            switch (logLevel)
            {
                case LogLevel.Warn:
                    logtype = LoggerTypes.Warning;
                    break;
                case LogLevel.Error:
                    logtype = LoggerTypes.FatalError;
                    break;
                case LogLevel.Info:
                    logtype = LoggerTypes.Info;
                    break;
                case LogLevel.Notice:
                    logtype = LoggerTypes.Success;
                    break;
            }

            MyLoger_here(message, logtype);
        }

............................................................................

//Logger is called here in my session this send message logs to my instance LoggerFucntion
                   ClientSession.Logger.RegisterLogOutput(LoggerFucntion);

```

**Comment by Furtif** [comment]
ops sorry lol bad button :s

**Comment by Xelwon** [comment]
I think this complicates the logic of use and does not give any benefit.
Currently, you can do a similar process in a simple line.

After of "getsession" function. Adding the next lines. 
```csharp
session.Logger.RegisterLogOutput((level, message) =>
                                                 {
                                                     switch (level)
                                                     {
                                                         case LogLevel.Debug:
                                                             Logger.Debug(message);
                                                             break;
                                                         case LogLevel.Info:
                                                             Logger.Info(message);
                                                             break;
                                                         case LogLevel.Notice:
                                                         case LogLevel.Warn:
                                                             Logger.Warn(message);
                                                             break;
                                                         case LogLevel.Error:
                                                             Logger.Error(message);
                                                             break;
                                                         default:
                                                             throw new ArgumentOutOfRangeException(nameof(level), level, null);
                                                     }
});
```

Can you say us the adventages that you see to your changes? Thanks

**Comment by PeterDM65** [comment]
1) Maybe you don't need it but try logging something in the ctor of Player, Map, Templates, RpcClient, HeartbeatDispatcher, Session, ...
2) For an outstander it seems to me it is much clearer. The ctor of session states clearly you need a logger (that you can properly initialise before using). As implemented it is not clear that you should call 'session.Logger.RegisterLogOutput' after creation of the session.
3)

**Pull request closed without merging**
